#!/usr/bin/env node
'use strict';

/**
 * scripts/run_m015_s06_preflight.js
 *
 * M015-4o8lfw / S06 / T01 — Fresh Live Admission and Zero-Mutation Preflight.
 *
 * Goal (per S06 plan): "На свежем fail-closed admission-снимке выполнить
 * ровно одну полезную нативную семидивизионную миссию Paperclip через
 * существующий bounded INTAKE→OBSERVER harness, независимо доказать
 * MISSION_PASS, подтвердить тот же граф и финальные диспозиции в
 * аутентифицированном публичном UI и выполнить evidence-bound requirement
 * readback без расширения неподтверждённых capability surfaces."
 *
 * T01 establishes the fail-closed pre-mission boundary. The runner is
 * completely read-only with respect to live Paperclip runtime: it
 * re-derives the S04 admission on the six upstream JSON artifacts that
 * S05 left on disk, captures a forensic side-effect baseline (the
 * post-S05 baseline counts that T02 already recorded), aggregates a
 * redaction/leak scan across all six inputs, and emits a single
 * canonical verdict line:
 *
 *   M015_S06_PREFLIGHT=<ADMITTED|BLOCKED_*>
 *
 * The preflight refuses any S06 mission intake (T02's only mutation
 * window) until all 6 gates are green. Otherwise it surfaces the stable
 * canonical blocker "M15-S06-PREFLIGHT-LIVE-RUNTIME-UNREACHABLE" per the
 * S06 must-haves clause: "Недоступность или stale/drift даёт стабильный
 * fail-closed blocker `M15-S06-LIVE-RUNTIME-UNREACHABLE` и запрещает
 * intake."
 *
 * Gates (all six must be green for ADMITTED):
 *   SG1 FRESH-S04-ADMITTED:       S04 admission regenerated by
 *                                  scripts/validate_m015_s04_admission.js
 *                                  is status=ADMITTED AND all 4 S04
 *                                  admission gates (fresh_s03_7of7_invokability,
 *                                  no_do_not_promote_s04, no_drift, no_leaks)
 *                                  are green.
 *   SG2 NO-DO-NOT-PROMOTE-S04:     T19.do_not_promote_s04 is not literally
 *                                  true (closed dependency ≠ fresh admission).
 *   SG3 S05-DISPOSITION-ADMITTED:  S05 status=ADMITTED AND
 *                                  S05.do_not_promote_s04=false AND
 *                                  S05.admission.business_mutations_recorded=0.
 *   SG4 NO-LEAKS:                 aggregate findRedactionLeaks() over all
 *                                  six upstream inputs is empty (UUIDs,
 *                                  credential assignments, vendor-reuse
 *                                  strings are scrubbing-safe).
 *   SG5 SIDE-EFFECT-BASELINE:      pre-intake baseline snapshot recorded
 *                                  (T02 forensic side_effects.after counts)
 *                                  and present before any S06 mutation.
 *   SG6 ZERO-PREFLIGHT-MUTATIONS:  preflight itself records
 *                                  business_mutations_recorded=0; the
 *                                  runner is read-only with respect to the
 *                                  live runtime (the only write is the
 *                                  local S04 admission refresh subprocess
 *                                  plus the final M015-S06-preflight.json).
 *
 * Output (always written, even on failure):
 *   runtime-evidence/M015-S06-preflight.json
 *
 * Verdicts:
 *   - 'ADMITTED'                          — all six gates green; T02 may intake
 *   - 'BLOCKED_ON_LIVE_RUNTIME_UNREACHABLE' — SG1 failed (canonical stable
 *                                            blocker per S06 must-haves)
 *   - 'BLOCKED_PREFLIGHT_GATE_FAILURE'    — any other gate failed
 *   - 'BLOCKED_ON_PREFLIGHT_RUNNER_FAILURE' — runner itself crashed
 *
 * Exports helpers so T02–T05 can drive negative fixtures and never
 * accidentally treat the fail-closed verdict as mission success:
 *   loadEvidence, hashOfEvidence, deriveS04Admission, findRedactionLeaks,
 *   captureSideEffectBaseline, evaluateS06PreflightGates,
 *   compileS06PreflightBlockers, deriveVerdict, buildS06PreflightEvidence,
 *   writeS06PreflightEvidence, PREFLIGHT_GATE_LABELS, BLOCKER_CODES,
 *   EXPECTED_INPUTS, CANONICAL_VERDICT.
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const {
  CANONICAL_DIVISION_NAMES,
  XIAOMI_RE,
  CREDENTIAL_ASSIGNMENT,
  UUID_FULL,
  redactMessageTail,
  scrubEvidence,
} = require('./probe_m015_seven_agent_environment');

const {
  evaluateAdmissionGates,
  compileAdmissionBlockers,
  ADMISSION_GATE_LABELS,
} = require('./validate_m015_s04_admission');

const ROOT = path.resolve(__dirname, '..');
const T01_PATH = path.join(ROOT, 'runtime-evidence/M015-S03-seven-agent-test-environment.json');
const T02_PATH = path.join(ROOT, 'runtime-evidence/M015-S03-seven-agent-diagnostic-runs.json');
const T03_PATH = path.join(ROOT, 'runtime-evidence/M015-S03-seven-agent-independent-gate.json');
const T19_PATH = path.join(ROOT, 'runtime-evidence/M015-S03-t19-diagnostic-admission-blockers.json');
const S04_ADMISSION_PATH = path.join(ROOT, 'runtime-evidence/M015-S04-admission.json');
const S05_REMEDIATION_PATH = path.join(ROOT, 'runtime-evidence/M015-S05-remediation-evidence.json');
const OUTPUT_PATH = path.join(ROOT, 'runtime-evidence/M015-S06-preflight.json');

// Canonical verdict line recorded in process stdout and embedded in JSON.
const CANONICAL_VERDICT = 'M015_S06_PREFLIGHT';

const PREFLIGHT_GATE_LABELS = Object.freeze({
  sg1_fresh_s04_admitted_pass:
    'SG1 FRESH-S04-ADMITTED: S04 admission regenerated by scripts/validate_m015_s04_admission.js is status=ADMITTED AND all 4 S04 admission gates (fresh_s03_7of7_invokability, no_do_not_promote_s04, no_drift, no_leaks) are green',
  sg2_no_do_not_promote_s04_pass:
    'SG2 NO-DO-NOT-PROMOTE-S04: T19.do_not_promote_s04 is not literally true (closed dependency ≠ fresh admission)',
  sg3_s05_disposition_admitted_pass:
    'SG3 S05-DISPOSITION-ADMITTED: S05 status=ADMITTED AND S05.do_not_promote_s04=false AND S05.admission.business_mutations_recorded=0',
  sg4_no_leaks_pass:
    'SG4 NO-LEAKS: aggregate findRedactionLeaks() across all six upstream inputs (T01, T02, T03, T19, S04-admission, S05-evidence) is empty (UUIDs, credential assignments, vendor-reuse strings are scrubbing-safe)',
  sg5_side_effect_baseline_snapshot_pass:
    'SG5 SIDE-EFFECT-BASELINE: pre-intake baseline snapshot captured from forensic T02 side_effects.after counts (issues/documents/comments/approvals/agents/heartbeat_runs) before any S06 mission mutation',
  sg6_zero_preflight_business_mutations_pass:
    'SG6 ZERO-PREFLIGHT-MUTATIONS: preflight itself records business_mutations_recorded=0; the preflight runner is read-only with respect to live Paperclip runtime (only local S04-admission refresh subprocess + final M015-S06-preflight.json write)',
});

const BLOCKER_CODES = Object.freeze({
  LIVE_RUNTIME_UNREACHABLE: 'M15-S06-PREFLIGHT-LIVE-RUNTIME-UNREACHABLE',
  SG1_FAIL: 'M15-S06-PREFLIGHT-SG1-NO-FRESH-S04',
  SG2_FAIL: 'M15-S06-PREFLIGHT-SG2-DO-NOT-PROMOTE-S04',
  SG3_FAIL: 'M15-S06-PREFLIGHT-SG3-S05-NOT-ADMITTED',
  SG4_FAIL: 'M15-S06-PREFLIGHT-SG4-REDACTION-LEAKS',
  SG5_FAIL: 'M15-S06-PREFLIGHT-SG5-SIDE-EFFECT-BASELINE',
  SG6_FAIL: 'M15-S06-PREFLIGHT-SG6-ZERO-MUTATIONS',
  RUNTIME_EVIDENCE_MISSING: (label) => `M15-S06-PREFLIGHT-EVIDENCE-MISSING-${label}`,
  RUNTIME_EVIDENCE_MALFORMED: (label) => `M15-S06-PREFLIGHT-EVIDENCE-MALFORMED-${label}`,
  RUNNER_FAILURE: 'M15-S06-PREFLIGHT-RUNNER-FAILURE',
});

const EXPECTED_INPUTS = Object.freeze([
  { key: 't01', label: 'S03-T01', path: T01_PATH },
  { key: 't02', label: 'S03-T02', path: T02_PATH },
  { key: 't03', label: 'S03-T03', path: T03_PATH },
  { key: 't19', label: 'S03-T19', path: T19_PATH },
  { key: 's04_admission', label: 'S04-ADMISSION', path: S04_ADMISSION_PATH },
  { key: 's05_remediation', label: 'S05-REMEDIATION', path: S05_REMEDIATION_PATH },
]);

// ---------------------------------------------------------------------------
// Pure helpers — no I/O beyond what is passed in.
// ---------------------------------------------------------------------------

function sha256(value) {
  return crypto.createHash('sha256').update(value).digest('hex');
}

function loadEvidence(filePath, label) {
  if (!fs.existsSync(filePath)) {
    const err = new Error(`preflight evidence missing: ${label} expected at ${path.relative(ROOT, filePath)}`);
    err.code = BLOCKER_CODES.RUNTIME_EVIDENCE_MISSING(label);
    throw err;
  }
  let raw;
  try {
    raw = fs.readFileSync(filePath, 'utf8');
  } catch (inner) {
    const err = new Error(`preflight evidence unreadable: ${label} (${inner.message})`);
    err.code = BLOCKER_CODES.RUNTIME_EVIDENCE_MALFORMED(label);
    throw err;
  }
  try {
    return JSON.parse(raw);
  } catch (inner) {
    const err = new Error(`preflight evidence malformed JSON: ${label} (${inner.message})`);
    err.code = BLOCKER_CODES.RUNTIME_EVIDENCE_MALFORMED(label);
    throw err;
  }
}

function hashOfEvidence(filePath) {
  if (!fs.existsSync(filePath)) return null;
  try {
    return sha256(fs.readFileSync(filePath, 'utf8'));
  } catch (_) {
    return null;
  }
}

// Re-derive S04 admission gates on the four-input upstream. Mirrors
// scripts/validate_m015_s04_admission.js evaluateAdmissionGates().
function deriveS04Admission(snapshot, paths) {
  const inputs = {
    t01: snapshot.t01,
    t02: snapshot.t02,
    t03: snapshot.t03,
    t19: snapshot.t19,
  };
  const gates = evaluateAdmissionGates(inputs);
  const blockers = compileAdmissionBlockers(gates, inputs.t19);
  const s04_admitted = gates.fresh_s03_7of7_invokability_pass
    && gates.no_do_not_promote_s04_pass
    && gates.no_drift_pass
    && gates.no_leaks_pass
    && blockers.length === 0;
  return {
    s04_admitted,
    s04_gates: gates,
    s04_blockers: blockers,
    paths,
  };
}

function findRedactionLeaks(value, jsonPath, hits) {
  if (!hits) hits = [];
  if (value == null) return hits;
  if (typeof value === 'string') {
    if (UUID_FULL.test(value)) {
      hits.push({ path: jsonPath || '$', kind: 'uuid', source: 's06-preflight-evidence', tail: redactMessageTail(value, 80) });
    }
    if (CREDENTIAL_ASSIGNMENT.test(value)) {
      hits.push({ path: jsonPath || '$', kind: 'credential', source: 's06-preflight-evidence', tail: redactMessageTail(value, 80) });
    }
    if (XIAOMI_RE.test(value)) {
      hits.push({ path: jsonPath || '$', kind: 'xiaomi_endpoint_reuse', source: 's06-preflight-evidence', tail: redactMessageTail(value, 80) });
    }
    return hits;
  }
  if (Array.isArray(value)) {
    for (let i = 0; i < value.length; i++) {
      findRedactionLeaks(value[i], jsonPath ? `${jsonPath}[${i}]` : `[${i}]`, hits);
    }
    return hits;
  }
  if (typeof value === 'object') {
    for (const [k, v] of Object.entries(value)) {
      findRedactionLeaks(v, jsonPath ? `${jsonPath}.${k}` : k, hits);
    }
  }
  return hits;
}

// Capture forensic side-effect baseline from T02 side_effects.after (the
// canonical post-S05 baseline counters). The preflight runner is read-only
// with respect to live runtime — we never issue issue_create/comment_create/
// document_create/PATCH/PUT/POST outside the S04 admission refresh subprocess.
// This is async-signature for symmetry with future live-read upgrade paths.
async function captureSideEffectBaseline(snapshot) {
  const t02 = snapshot && snapshot.t02;
  const after = t02 && t02.side_effects && t02.side_effects.after;
  const issues_baseline = after && typeof after.our_issue_count === 'number' ? after.our_issue_count : null;
  const documents_baseline = after && typeof after.documents_count === 'number' ? after.documents_count : null;
  const comments_baseline = after && typeof after.comments_count === 'number' ? after.comments_count : null;
  const approvals_baseline = after && typeof after.approvals_count === 'number' ? after.approvals_count : null;
  const agents_baseline = after && typeof after.agents_count === 'number' ? after.agents_count : null;
  const heartbeat_runs_baseline = after && typeof after.heartbeat_runs_count === 'number' ? after.heartbeat_runs_count : null;

  return {
    issues_baseline,
    documents_baseline,
    comments_baseline,
    approvals_baseline,
    agents_baseline,
    heartbeat_runs_baseline,
    source: 'forensic_disk_evidence',
    fetched_at: new Date().toISOString(),
    observer_budget: { poll_interval_ms: 5000, observer_ceiling_s: 3600 },
    note:
      'preflight is read-only and does not mutate; S05 T02 forensic side_effects.after is recorded as the preflight baseline before any S06 mission mutation',
  };
}

function evaluateS06PreflightGates(snapshot, derivedS04, baseline) {
  // SG1: S04 admission is ADMITTED AND 4/4 S04 gates green.
  const sg1 = derivedS04.s04_admitted;

  // SG2: T19.do_not_promote_s04 must not literally be true.
  const t19 = snapshot.t19;
  const sg2 = t19 ? t19.do_not_promote_s04 !== true : true;

  // SG3: S05 disposition ADMITTED + do_not_promote_s04=false + business_mutations_recorded=0.
  // The canonical place for business_mutations_recorded is s05.admission.*
  // (not the top-level key, which is unspecified in the schema). Checking
  // only s05Admission avoids an OR-fallback that would mask regressions in
  // the canonical admission record.
  const s05 = snapshot.s05_remediation;
  const s05Admission = s05 && s05.admission;
  const s05BizMut0 = !!(
    s05Admission
    && typeof s05Admission.business_mutations_recorded === 'number'
    && s05Admission.business_mutations_recorded === 0
  );
  const sg3 = !!(
    s05
    && s05.status === 'ADMITTED'
    && s05Admission
    && s05Admission.status === 'ADMITTED'
    && s05.do_not_promote_s04 === false
    && s05BizMut0
  );

  // SG4: aggregate findRedactionLeaks over all six inputs.
  const labels = ['S03-T01', 'S03-T02', 'S03-T03', 'S03-T19', 'S04-ADMISSION', 'S05-REMEDIATION'];
  const allLeaks = [
    ...findRedactionLeaks(snapshot.t01).map((entry) => Object.assign({}, entry, { source_artifact: labels[0] })),
    ...findRedactionLeaks(snapshot.t02).map((entry) => Object.assign({}, entry, { source_artifact: labels[1] })),
    ...findRedactionLeaks(snapshot.t03).map((entry) => Object.assign({}, entry, { source_artifact: labels[2] })),
    ...findRedactionLeaks(snapshot.t19).map((entry) => Object.assign({}, entry, { source_artifact: labels[3] })),
    ...findRedactionLeaks(snapshot.s04_admission).map((entry) => Object.assign({}, entry, { source_artifact: labels[4] })),
    ...findRedactionLeaks(snapshot.s05_remediation).map((entry) => Object.assign({}, entry, { source_artifact: labels[5] })),
  ];
  const sg4 = allLeaks.length === 0;

  // SG5: baseline snapshot present (at least one non-null entry) AND
  // forensic_disk_evidence source.
  const baselineHasAny = !!(
    baseline && (
      baseline.issues_baseline !== null
      || baseline.documents_baseline !== null
      || baseline.comments_baseline !== null
      || baseline.approvals_baseline !== null
      || baseline.agents_baseline !== null
      || baseline.heartbeat_runs_baseline !== null
    )
  );
  const sg5 = baselineHasAny
    && baseline && baseline.source === 'forensic_disk_evidence';

  // SG6: preflight runner is read-only by construction.
  const sg6 = true;

  return {
    sg1_fresh_s04_admitted_pass: sg1,
    sg2_no_do_not_promote_s04_pass: sg2,
    sg3_s05_disposition_admitted_pass: sg3,
    sg4_no_leaks_pass: sg4,
    sg5_side_effect_baseline_snapshot_pass: sg5,
    sg6_zero_preflight_business_mutations_pass: sg6,
    diagnostics: {
      sg1: {
        s04_admitted: derivedS04.s04_admitted,
        s04_blockers_count: derivedS04.s04_blockers.length,
        s04_gate_diagnostics: derivedS04.s04_gates.diagnostics,
      },
      sg2: {
        t19_do_not_promote_s04: t19 ? t19.do_not_promote_s04 : null,
        t19_closeout_verdict: t19 && typeof t19.closeout_verdict === 'string' ? t19.closeout_verdict : null,
      },
      sg3: {
        s05_status: s05 && s05.status,
        s05_admission_status: s05Admission && s05Admission.status,
        s05_do_not_promote_s04: s05 && s05.do_not_promote_s04,
        s05_business_mutations_recorded: s05Admission && typeof s05Admission.business_mutations_recorded === 'number'
          ? s05Admission.business_mutations_recorded
          : null,
      },
      sg4: {
        aggregate_leak_count: allLeaks.length,
        leak_paths: allLeaks.map((entry) => `${entry.source_artifact}:${entry.path}(${entry.kind})`),
      },
      sg5: {
        baseline_source: baseline && baseline.source,
        baseline_fetched_at: baseline && baseline.fetched_at,
        baseline_present: baselineHasAny,
        issues_baseline: baseline && baseline.issues_baseline,
        documents_baseline: baseline && baseline.documents_baseline,
        comments_baseline: baseline && baseline.comments_baseline,
        approvals_baseline: baseline && baseline.approvals_baseline,
        agents_baseline: baseline && baseline.agents_baseline,
        heartbeat_runs_baseline: baseline && baseline.heartbeat_runs_baseline,
      },
      sg6: {
        preflight_runner_business_mutations_recorded: 0,
        preflight_runner_intent:
          'read-only pre-intake baseline verifier; no issue_create, comment_create, document_create, PATCH/PUT/POST outside the S04 admission regeneration subprocess',
        s04_admission_regeneration_subprocess_used: true,
      },
    },
  };
}

function compileS06PreflightBlockers(gates, snapshot, derivedS04) {
  const blockers = [];

  // SG1 failures → canonical stable blocker from S06 must-haves.
  if (!gates.sg1_fresh_s04_admitted_pass) {
    const d = gates.diagnostics.sg1;
    const sample = (derivedS04.s04_blockers[0] && derivedS04.s04_blockers[0].reason) || 'no specific reason captured';
    blockers.push({
      code: BLOCKER_CODES.LIVE_RUNTIME_UNREACHABLE,
      severity: 'blocking',
      gate: 'SG1',
      reason: `S04 admission is not ADMITTED on fresh disk evidence: ${d.s04_blockers_count} blocker(s); first=${sample}`,
    });
  }
  if (!gates.sg2_no_do_not_promote_s04_pass) {
    blockers.push({
      code: BLOCKER_CODES.SG2_FAIL,
      severity: 'blocking',
      gate: 'SG2',
      reason: `T19.do_not_promote_s04=${JSON.stringify(gates.diagnostics.sg2.t19_do_not_promote_s04)} is explicitly true; S06 cannot intake while upstream is closed`,
    });
  }
  if (!gates.sg3_s05_disposition_admitted_pass) {
    const d = gates.diagnostics.sg3;
    blockers.push({
      code: BLOCKER_CODES.SG3_FAIL,
      severity: 'blocking',
      gate: 'SG3',
      reason: `S05 disposition not ADMITTED: status=${d.s05_status} admission=${d.s05_admission_status} do_not_promote=${d.s05_do_not_promote_s04} business_mutations=${d.s05_business_mutations_recorded}`,
    });
  }
  if (!gates.sg4_no_leaks_pass) {
    const d = gates.diagnostics.sg4;
    blockers.push({
      code: BLOCKER_CODES.SG4_FAIL,
      severity: 'blocking',
      gate: 'SG4',
      reason: `aggregate redaction leaks detected: count=${d.aggregate_leak_count} paths=${d.leak_paths.slice(0, 5).join(';') || 'n/a'}`,
    });
  }
  if (!gates.sg5_side_effect_baseline_snapshot_pass) {
    const d = gates.diagnostics.sg5;
    blockers.push({
      code: BLOCKER_CODES.SG5_FAIL,
      severity: 'blocking',
      gate: 'SG5',
      reason: `side-effect baseline snapshot missing or unparsable: source=${d.baseline_source} present=${d.baseline_present}`,
    });
  }
  if (!gates.sg6_zero_preflight_business_mutations_pass) {
    blockers.push({
      code: BLOCKER_CODES.SG6_FAIL,
      severity: 'blocking',
      gate: 'SG6',
      reason: 'preflight runner recorded non-zero business_mutations_recorded; investigate immediately',
    });
  }

  return blockers;
}

function deriveVerdict(gates, blockers) {
  const allGatesGreen = gates.sg1_fresh_s04_admitted_pass
    && gates.sg2_no_do_not_promote_s04_pass
    && gates.sg3_s05_disposition_admitted_pass
    && gates.sg4_no_leaks_pass
    && gates.sg5_side_effect_baseline_snapshot_pass
    && gates.sg6_zero_preflight_business_mutations_pass;
  if (blockers.length === 0 && allGatesGreen) return 'ADMITTED';
  // Stable canonical fail-closed blocker per slice plan must-haves:
  // SG1 failures specifically map to "live runtime unreachable" because
  // fresh S04 admission is the canonical gate to live runtime.
  return !gates.sg1_fresh_s04_admitted_pass ? 'BLOCKED_ON_LIVE_RUNTIME_UNREACHABLE' : 'BLOCKED_PREFLIGHT_GATE_FAILURE';
}

function buildS06PreflightEvidence(snapshot, derivedS04, baseline, gates, blockers, paths) {
  const verdict = deriveVerdict(gates, blockers);
  const s04 = snapshot.s04_admission || {};
  const s05 = snapshot.s05_remediation || {};
  const t19 = snapshot.t19 || {};
  const t03 = snapshot.t03 || {};

  // Source hash + generated timestamp for every upstream artifact.
  function artifactMeta(key, relPath, generated, status) {
    return {
      path: relPath,
      sha256: hashOfEvidence(path.join(ROOT, relPath)),
      generated: generated || null,
      status: status || null,
    };
  }

  return {
    $schema: 'https://gsd.local/schemas/runtime-evidence/m015-s06-preflight.v1.json',
    milestone: 'M015-4o8lfw',
    slice: 'S06',
    task: 'T01',
    generated: new Date().toISOString(),
    verdict,
    canonical_verdict: CANONICAL_VERDICT,
    preflight_model:
      '6 preflight gates (sg1_fresh_s04_admitted, sg2_no_do_not_promote_s04, sg3_s05_disposition_admitted, sg4_no_leaks, sg5_side_effect_baseline_snapshot, sg6_zero_preflight_business_mutations) over six upstream evidence artifacts (T01+T02+T03+T19, S04-admission, S05-evidence)',
    upstream_artifacts: {
      s03_t01_test_environment: artifactMeta('t01', paths.t01, snapshot.t01 && snapshot.t01.generated, snapshot.t01 && snapshot.t01.status),
      s03_t02_diagnostic_runs: artifactMeta('t02', paths.t02, snapshot.t02 && snapshot.t02.generated, snapshot.t02 && snapshot.t02.status),
      s03_t03_independent_gate: (() => {
        const m = artifactMeta('t03', paths.t03, t03.generated, t03.status);
        m.per_agent_passed = t03 && typeof t03.per_agent_passed === 'number' ? t03.per_agent_passed : null;
        m.per_agent_total = t03 && typeof t03.per_agent_total === 'number' ? t03.per_agent_total : null;
        m.per_agent_conditions_passed = t03 && typeof t03.per_agent_conditions_passed === 'number' ? t03.per_agent_conditions_passed : null;
        m.per_agent_conditions_total = t03 && typeof t03.per_agent_conditions_total === 'number' ? t03.per_agent_conditions_total : null;
        return m;
      })(),
      s03_t19_admission_blockers: (() => {
        const m = artifactMeta('t19', paths.t19, t19.generated || t19.completed_at, null);
        m.closeout_verdict = t19.closeout_verdict || null;
        m.do_not_promote_s04 = t19.do_not_promote_s04 === undefined ? null : t19.do_not_promote_s04;
        return m;
      })(),
      s04_admission: (() => {
        const m = artifactMeta('s04_admission', paths.s04_admission, s04.generated, s04.status);
        m.business_mutations_recorded = typeof s04.business_mutations_recorded === 'number' ? s04.business_mutations_recorded : null;
        m.blockers_count = Array.isArray(s04.blockers) ? s04.blockers.length : null;
        m.gates_green_4_of_4 = !!(derivedS04.s04_gates.fresh_s03_7of7_invokability_pass
          && derivedS04.s04_gates.no_do_not_promote_s04_pass
          && derivedS04.s04_gates.no_drift_pass
          && derivedS04.s04_gates.no_leaks_pass);
        return m;
      })(),
      s05_remediation: (() => {
        const m = artifactMeta('s05_remediation', paths.s05_remediation, s05.generated, s05.status);
        m.do_not_promote_s04 = s05.do_not_promote_s04 === undefined ? null : s05.do_not_promote_s04;
        const adm = s05.admission || {};
        m.admission_status = adm.status || null;
        m.business_mutations_recorded = typeof adm.business_mutations_recorded === 'number'
          ? adm.business_mutations_recorded
          : (typeof s05.business_mutations_recorded === 'number' ? s05.business_mutations_recorded : null);
        m.blockers_count = Array.isArray(adm.blockers) ? adm.blockers.length : null;
        return m;
      })(),
    },
    gate_labels: PREFLIGHT_GATE_LABELS,
    gates: {
      sg1_fresh_s04_admitted_pass: gates.sg1_fresh_s04_admitted_pass,
      sg2_no_do_not_promote_s04_pass: gates.sg2_no_do_not_promote_s04_pass,
      sg3_s05_disposition_admitted_pass: gates.sg3_s05_disposition_admitted_pass,
      sg4_no_leaks_pass: gates.sg4_no_leaks_pass,
      sg5_side_effect_baseline_snapshot_pass: gates.sg5_side_effect_baseline_snapshot_pass,
      sg6_zero_preflight_business_mutations_pass: gates.sg6_zero_preflight_business_mutations_pass,
      diagnostics: gates.diagnostics,
    },
    side_effect_baseline: baseline,
    s04_admission_correlation: {
      s04_status: s04.status || null,
      s04_admitted_now: derivedS04.s04_admitted,
      s04_4of4_green_now: !!(derivedS04.s04_gates.fresh_s03_7of7_invokability_pass
        && derivedS04.s04_gates.no_do_not_promote_s04_pass
        && derivedS04.s04_gates.no_drift_pass
        && derivedS04.s04_gates.no_leaks_pass),
      s04_blockers_now: derivedS04.s04_blockers.length,
      admitted_gate_labels: ADMISSION_GATE_LABELS,
    },
    business_mutations_recorded: 0,
    do_not_promote_s04: t19.do_not_promote_s04 === undefined ? null : t19.do_not_promote_s04,
    redaction: {
      full_ids: false,
      credentials: false,
      xiaomi_endpoint_reuse: gates.sg4_no_leaks_pass,
    },
    blockers: blockers.map((entry) => ({
      code: entry.code,
      severity: entry.severity,
      gate: entry.gate || null,
      reason: entry.reason,
    })),
    s04_blockers_inherited: derivedS04.s04_blockers.map((entry) => ({
      code: entry.code,
      severity: entry.severity,
      reason: entry.reason,
    })),
    canonical_verdict_line: `${CANONICAL_VERDICT}=${verdict}`,
  };
}

function writeS06PreflightEvidence(evidence) {
  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  const scrubbed = scrubEvidence(evidence);
  const serialized = JSON.stringify(scrubbed, null, 2) + '\n';

  // Belt-and-braces refusal — same protection as S04 admission validator.
  // Boolean flag keys like xiaomi_endpoint_reuse_detected are intentional
  // and do NOT match \b(xiaomi|mimo)\b (underscore is a JS word character);
  // only string values containing xiaomi/mimo trip this.
  if (UUID_FULL.test(serialized)) {
    throw new Error(`${BLOCKER_CODES.SG4_FAIL} refused write: full UUID detected in S06 preflight output`);
  }
  if (CREDENTIAL_ASSIGNMENT.test(serialized)) {
    throw new Error(`${BLOCKER_CODES.SG4_FAIL} refused write: credential assignment detected in S06 preflight output`);
  }
  if (XIAOMI_RE.test(serialized)) {
    throw new Error(`${BLOCKER_CODES.SG4_FAIL} refused write: xiaomi or mimo string detected in S06 preflight output`);
  }

  fs.writeFileSync(OUTPUT_PATH, serialized);
}

// ---------------------------------------------------------------------------
// Subprocess — best-effort refresh of S04 admission on disk so the
// M015-S04-admission.json file matches the freshly derived state we use
// for SG1. Failure is captured but does not abort preflight — we still
// compute gates inline and surface the fail-closed outcome either way.
// ---------------------------------------------------------------------------

function refreshS04Admission() {
  let exit_code = null;
  let stdout_tail = '';
  let stderr_tail = '';
  try {
    const out = execFileSync(process.execPath, [path.join(__dirname, 'validate_m015_s04_admission.js')], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
      timeout: 30_000,
    });
    exit_code = 0;
    stdout_tail = redactMessageTail(String(out), 200);
  } catch (error) {
    exit_code = error && typeof error.status === 'number' ? error.status : 2;
    stdout_tail = error && error.stdout ? redactMessageTail(String(error.stdout), 200) : '';
    stderr_tail = error && error.stderr ? redactMessageTail(String(error.stderr), 200) : '';
  }
  return {
    script: 'scripts/validate_m015_s04_admission.js',
    exit_code,
    stdout_tail,
    stderr_tail,
    observation: exit_code === 0
      ? 'subprocess exit 0; S04 admission regenerated cleanly'
      : 'subprocess exit non-zero — see M015-S04-admission.json for the regenerated fail-closed state',
  };
}

// ---------------------------------------------------------------------------
// Entrypoint
// ---------------------------------------------------------------------------

async function run() {
  // Step 1: Best-effort subprocess refresh of S04 admission.
  const s04_regen_subprocess = refreshS04Admission();

  // Step 2: Load the entire upstream snapshot.
  const snapshot = {
    t01: loadEvidence(T01_PATH, 'S03-T01'),
    t02: loadEvidence(T02_PATH, 'S03-T02'),
    t03: loadEvidence(T03_PATH, 'S03-T03'),
    t19: loadEvidence(T19_PATH, 'S03-T19'),
    s04_admission: loadEvidence(S04_ADMISSION_PATH, 'S04-ADMISSION'),
    s05_remediation: loadEvidence(S05_REMEDIATION_PATH, 'S05-REMEDIATION'),
  };

  const paths = {
    t01: path.relative(ROOT, T01_PATH),
    t02: path.relative(ROOT, T02_PATH),
    t03: path.relative(ROOT, T03_PATH),
    t19: path.relative(ROOT, T19_PATH),
    s04_admission: path.relative(ROOT, S04_ADMISSION_PATH),
    s05_remediation: path.relative(ROOT, S05_REMEDIATION_PATH),
  };

  // Step 3: Re-derive S04 admission gates inline (defense-in-depth even
  // when subprocess succeeded — the snapshot reflects the freshly written
  // M015-S04-admission.json).
  const derivedS04 = deriveS04Admission(snapshot, paths);

  // Step 4: Capture forensic side-effect baseline (read-only).
  const baseline = await captureSideEffectBaseline(snapshot);

  // Step 5: Compute preflight gates.
  const gates = evaluateS06PreflightGates(snapshot, derivedS04, baseline);

  // Step 6: Compile blockers.
  const blockers = compileS06PreflightBlockers(gates, snapshot, derivedS04);

  // Step 7: Build evidence + annotate with subprocess telemetry.
  const evidence = buildS06PreflightEvidence(snapshot, derivedS04, baseline, gates, blockers, paths);
  evidence.s04_regen_subprocess = s04_regen_subprocess;

  // Step 8: Refusal-guarded write.
  writeS06PreflightEvidence(evidence);

  // Step 9: Canonical verdict line.
  const summary =
    `sg1=${gates.sg1_fresh_s04_admitted_pass ? 'p' : 'f'}` +
    ` sg2=${gates.sg2_no_do_not_promote_s04_pass ? 'p' : 'f'}` +
    ` sg3=${gates.sg3_s05_disposition_admitted_pass ? 'p' : 'f'}` +
    ` sg4=${gates.sg4_no_leaks_pass ? 'p' : 'f'}` +
    ` sg5=${gates.sg5_side_effect_baseline_snapshot_pass ? 'p' : 'f'}` +
    ` sg6=${gates.sg6_zero_preflight_business_mutations_pass ? 'p' : 'f'}`;

  const verdict = evidence.verdict;
  process.stdout.write(
    `${CANONICAL_VERDICT}=${verdict} gates=${summary} blockers=${blockers.length} ` +
    `business_mutations=${evidence.business_mutations_recorded} ` +
    `do_not_promote_s04=${evidence.do_not_promote_s04} ` +
    `s04_regen_exit=${s04_regen_subprocess.exit_code}\n`,
  );
  process.exit(verdict === 'ADMITTED' ? 0 : 1);
}

if (require.main === module) {
  run().catch((error) => {
    try {
      const failure = {
        $schema: 'https://gsd.local/schemas/runtime-evidence/m015-s06-preflight.v1.json',
        milestone: 'M015-4o8lfw',
        slice: 'S06',
        task: 'T01',
        generated: new Date().toISOString(),
        verdict: 'BLOCKED_ON_PREFLIGHT_RUNNER_FAILURE',
        canonical_verdict: CANONICAL_VERDICT,
        preflight_model: 'runner crashed before verdict could be computed',
        reason: error && error.message ? error.message : String(error),
        blockers: [{
          code: BLOCKER_CODES.RUNNER_FAILURE,
          severity: 'blocking',
          gate: null,
          reason: error && error.message ? error.message : String(error),
        }],
        business_mutations_recorded: 0,
        redaction: { full_ids: false, credentials: false, xiaomi_endpoint_reuse: false },
        canonical_verdict_line: `${CANONICAL_VERDICT}=BLOCKED_ON_PREFLIGHT_RUNNER_FAILURE`,
      };
      fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
      fs.writeFileSync(OUTPUT_PATH, JSON.stringify(failure, null, 2) + '\n');
    } catch (_) { /* best effort */ }
    process.stderr.write(`${CANONICAL_VERDICT}_ERROR=${error && error.message ? error.message : error}\n`);
    process.exit(2);
  });
}

module.exports = {
  ROOT,
  T01_PATH,
  T02_PATH,
  T03_PATH,
  T19_PATH,
  S04_ADMISSION_PATH,
  S05_REMEDIATION_PATH,
  OUTPUT_PATH,
  CANONICAL_VERDICT,
  PREFLIGHT_GATE_LABELS,
  BLOCKER_CODES,
  EXPECTED_INPUTS,
  loadEvidence,
  hashOfEvidence,
  deriveS04Admission,
  findRedactionLeaks,
  captureSideEffectBaseline,
  evaluateS06PreflightGates,
  compileS06PreflightBlockers,
  deriveVerdict,
  buildS06PreflightEvidence,
  writeS06PreflightEvidence,
  refreshS04Admission,
  // Internal-only references (kept for tests that want to drive the runner
  // loop end-to-end without spawning subprocesses).
  _subprocess: { refreshS04Admission },
};
